// Generated by https://quicktype.io

export interface IPatient {
    name:      string;
    email:     string;
    patientid: number;
    phone:     string;
    weight:    string;
    height:    string;
    otherInfo: string;
}
